import { Container } from "@components/global";
import { Exercise } from "@types";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Exercises() {
  const [exercises, setExercises] = useState<Exercise[]>([]);
  useEffect(() => {
    if (typeof window !== "undefined") {
      const ls = JSON.parse(localStorage.getItem("exercises") ?? "[]");
      setExercises(ls);
      if (ls.length === 0) {
        localStorage.setItem("exercises", JSON.stringify([]));
      }
    }
  }, []);

  const transition = "transition ease-in duration-200";

  return (
    <>
      <Head>
        <title>Lifts of the North Star</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-24">
        <Container>
          <ul>
            <li>
              <button
                className={`${transition} border border-slate-900/10 dark:border-slate-100/10 rounded-md px-6 py-3 hover:-translate-y-1`}
              >
                <i className="fa-solid fa-dumbbell"></i>{" "}
                <strong>Add new</strong>
              </button>
            </li>
            {exercises.map(({ id, name }) => (
              <li key={id}>{name}</li>
            ))}
          </ul>
        </Container>
      </main>
    </>
  );
}
